package ma_caisse_final_version;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * @author Moses
 */
public class operation extends javax.swing.JInternalFrame {

    private final String url = "jdbc:mysql://127.0.0.1:3306/caisse", user = "root", pass = "";
    private Connection con;
    private Statement st;

    void ouverture() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            this.con = (Connection) DriverManager.getConnection(url, user, pass);
            System.out.println("ouvert");
        } catch (Exception e) {
            System.out.println("pas ouvert" + e);
        }
    }

    void fermeture() {
        try {
            this.con.close();
            this.st.close();
        } catch (Exception e) {
        }
    }

    public operation() {
        initComponents();
        placeholder jo = new placeholder("Votre nom", nom);
        jo = new placeholder("Mot de passe", mdp);
        jo = new placeholder("Montant", insert);
        valide.setVisible(false);
        Timer updateTimer;
        int play = 100;
        updateTimer = new Timer(play, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date cur = new Date();
                String FormatTimer = "hh:mm:ss";
                String FormatTimer2 = "dd/MM/yyyy";
                DateFormat as = new SimpleDateFormat(FormatTimer);
                DateFormat ase = new SimpleDateFormat(FormatTimer2);
                String a = as.format(cur);
                String b = ase.format(cur);
                heure.setText(a);
                date.setText(b);
            }
        });
        updateTimer.start();
        this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        heure = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mdp = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        post = new javax.swing.JTextField();
        valide = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        franc = new javax.swing.JTextField();
        dollar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        retrait = new javax.swing.JRadioButton();
        depot = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        Franc = new javax.swing.JRadioButton();
        Dollar = new javax.swing.JRadioButton();
        total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        insert = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Roblox Font", 1, 36)); // NOI18N
        jLabel2.setText("OPerations");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        date.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));

        heure.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        heure.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_user_32px.png"))); // NOI18N

        nom.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nom.setBorder(null);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_password_32px.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        mdp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        mdp.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Verification");

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("VERIFIER");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Complement", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("PRENOM   :");

        pre.setEditable(false);
        pre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("POSTNOM:");

        post.setEditable(false);
        post.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pre, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        valide.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Solde", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        franc.setEditable(false);
        franc.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        dollar.setEditable(false);
        dollar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("FC");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("$");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(franc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(45, 45, 45)
                .addComponent(dollar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(franc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dollar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Faire Un", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        buttonGroup1.add(retrait);
        retrait.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        retrait.setText("RETRAIT");
        retrait.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonGroup1.add(depot);
        depot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        depot.setText("DEPOT");
        depot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depot)
                .addGap(18, 18, 18)
                .addComponent(retrait)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depot)
                    .addComponent(retrait))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Devise", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        buttonGroup2.add(Franc);
        Franc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Franc.setText("FRANC");
        Franc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonGroup2.add(Dollar);
        Dollar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Dollar.setText("DOLLAR");
        Dollar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Franc)
                .addGap(18, 18, 18)
                .addComponent(Dollar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Franc)
                    .addComponent(Dollar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        total.setEditable(false);
        total.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Montant");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("TOTAL");

        jButton2.setBackground(new java.awt.Color(0, 255, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton2.setText("VALIDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        insert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout valideLayout = new javax.swing.GroupLayout(valide);
        valide.setLayout(valideLayout);
        valideLayout.setHorizontalGroup(
            valideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valideLayout.createSequentialGroup()
                .addGroup(valideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(valideLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(valideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(valideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(valideLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(valideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addGroup(valideLayout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel10))
                                    .addComponent(insert)))
                            .addGroup(valideLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel9))
                            .addGroup(valideLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jButton2))))
                    .addGroup(valideLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        valideLayout.setVerticalGroup(
            valideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valideLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(valideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(valideLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(valideLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 527, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heure, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(heure, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        verifier_le_client(nom.getText(), mdp.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (insert.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Inserer un montant valide");
        } else {
            operation();
        }
        insert.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Dollar;
    private javax.swing.JRadioButton Franc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel date;
    private javax.swing.JRadioButton depot;
    private javax.swing.JTextField dollar;
    private javax.swing.JTextField franc;
    private javax.swing.JLabel heure;
    private javax.swing.JTextField insert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField mdp;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField post;
    private javax.swing.JTextField pre;
    private javax.swing.JRadioButton retrait;
    private javax.swing.JTextField total;
    private javax.swing.JPanel valide;
    // End of variables declaration//GEN-END:variables

    public void verifier_le_client(String NOM, String CODE) {
        try {
            ouverture();
            Statement stm = (Statement) con.createStatement();
            String sql = "select * from ajoutclient where NOM ='" + NOM + "' and code = '" + CODE + "'";
            ResultSet rs = stm.executeQuery(sql);
            if (rs.next()) {
                completer_le_postnom(NOM, CODE);
                completer_le_prenom(NOM, CODE);
                valide.setVisible(true);
                ballance_franc(NOM, CODE);
                ballance_dollar(NOM, CODE);

            } else {
                JOptionPane.showMessageDialog(this, "Oups!! \nNom ou Mot de passe incorrect");
                valide.setVisible(false);
                nom.setText("");
                mdp.setText(null);
                post.setText("");
                pre.setText("");
            }
            fermeture();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pas de verificatioin");

        }
    }

    public void ballance_franc(String NOM, String CODE) {
        try {
            ouverture();
            Statement stm = (Statement) con.createStatement();
            String sql = "select total from franc where NOM ='" + NOM + "' and code = '" + CODE + "'";
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                double mm = rs.getDouble("total");
                franc.setText("" + mm);
            }
            fermeture();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pas de verificatioin");
        }
    }

    public void ballance_dollar(String NOM, String CODE) {
        try {
            ouverture();
            Statement stm = (Statement) con.createStatement();
            String sql = "select total from dollar where NOM ='" + NOM + "' and code = '" + CODE + "'";
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                double mm = rs.getDouble("total");
                dollar.setText("" + mm);
            }
            fermeture();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pas de verificatioin");
        }
    }

    public void completer_le_postnom(String Nom, String Code) {
        try {
            ouverture();
            this.st = (Statement) this.con.createStatement();
            String rech = "Select postnom from ajoutclient where nom='" + Nom + "' and code='" + Code + "'  ";
            ResultSet rs = this.st.executeQuery(rech);
            while (rs.next()) {
                String n = rs.getString("postnom");
                post.setText(n);
            }
            fermeture();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "non complet");
        }
    }

    public void completer_le_prenom(String Nom, String Code) {
        try {
            ouverture();
            this.st = (Statement) this.con.createStatement();
            String rech = "Select prenom from ajoutclient where nom='" + Nom + "' and code='" + Code + "' ";
            ResultSet rs = this.st.executeQuery(rech);
            while (rs.next()) {
                String n = rs.getString("prenom");
                pre.setText(n);
            }
            fermeture();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "non complet");
        }
    }

    public void operation() {
        //depot
        String faire = "";
        if (depot.isSelected() && Franc.isSelected()) {
            faire = depot.getText();
            double montant_actuel = Double.parseDouble(franc.getText());
            double montant_inserer = montant_actuel + Double.parseDouble(insert.getText());
            total.setText(" " + montant_inserer);
            //mettre dans la base de donnees
            add_franc(nom.getText(), pre.getText(), mdp.getText(), faire, insert.getText(), "" + montant_inserer, date.getText(), heure.getText());
        } else if (depot.isSelected() && Dollar.isSelected()) {
            faire = depot.getText();
            double montant_actuel = Double.parseDouble(dollar.getText());
            double montant_total = montant_actuel + Double.parseDouble(insert.getText());
            total.setText("" + montant_total);
            //mettre dans la base de donnees
            add_dollar(nom.getText(), pre.getText(), mdp.getText(), faire, insert.getText(), "" + montant_total, date.getText(), heure.getText());
        } //Retrait
        else if (retrait.isSelected() && Franc.isSelected()) {
            faire = retrait.getText();
            double in = Double.parseDouble(insert.getText());
            double fc = Double.parseDouble(franc.getText());
            if (in < fc || in <= 0) {
                double montant_total = fc - in;
                total.setText("" + montant_total);
                //mettre dans la base de donnees
                dell_franc(nom.getText(), pre.getText(), mdp.getText(), faire, "" + in, "" + montant_total, date.getText(), heure.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Solde insuffisant");
            }
        } else if (retrait.isSelected() && Dollar.isSelected()) {
            faire = retrait.getText();
            double in = Double.parseDouble(insert.getText());
            double dl = Double.parseDouble(dollar.getText());
            if (in < dl || in <= 0) {
                double montant_total = dl - in;
                total.setText("" + montant_total);
                //mettre dans la base de donnees
                dell_dollar(nom.getText(), pre.getText(), mdp.getText(), faire, "" + in, "" + montant_total, date.getText(), heure.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Solde inssufusant");
            }
        } //Aucun choix
        else {
            JOptionPane.showMessageDialog(null, "Choisir une option");
        }
    }

    //pour le franc
    public void add_franc(String Nom, String Prenom, String Code, String Motif, String Mt_ins, String Mt_tt, String Date, String Heure) {
        try {
            ouverture();
            this.st = (Statement) this.con.createStatement();
            String Insert = "insert into franc value('" + Nom + "','" + Prenom + "','" + Code + "','" + Motif + "','" + Mt_ins + "','" + Mt_tt + "','" + Date + " " + Heure + "')";
            this.st.executeUpdate(Insert);
            fermeture();
            JOptionPane.showMessageDialog(null, "Depot effectuer");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pas de depot " + e);
        }
    }

    //pour le dollar
    public void add_dollar(String Nom, String Prenom, String Code, String Motif, String Mt_ins, String Mt_tt, String Date, String Heure) {
        try {
            ouverture();
            this.st = (Statement) this.con.createStatement();
            String Insert = "insert into dollar value('" + Nom + "','" + Prenom + "','" + Code + "','" + Motif + "','" + Mt_ins + "','" + Mt_tt + "','" + Date + " " + Heure + "')";
            this.st.executeUpdate(Insert);
            fermeture();
            JOptionPane.showMessageDialog(null, "Depot effectuer");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pas de depot " + e);
        }
    }

    //retrancher le franc
    public void dell_franc(String Nom, String Prenom, String Code, String Motif, String Mt_ins, String Mt_tt, String Date, String Heure) {
        try {
            ouverture();
            this.st = (Statement) this.con.createStatement();
            String Insert = "insert into franc value('" + Nom + "','" + Prenom + "','" + Code + "','" + Motif + "','" + Mt_ins + "','" + Mt_tt + "','" + Date + " " + Heure + "')";
            this.st.executeUpdate(Insert);
            fermeture();
            JOptionPane.showMessageDialog(null, "Retrait effectuer");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pas de retrait " + e);
        }
    }

    //retrancher le dollar
    public void dell_dollar(String Nom, String Prenom, String Code, String Motif, String Mt_ins, String Mt_tt, String Date, String Heure) {
        try {
            ouverture();
            this.st = (Statement) this.con.createStatement();
            String Insert = "insert into dollar value('" + Nom + "','" + Prenom + "','" + Code + "','" + Motif + "','" + Mt_ins + "','" + Mt_tt + "','" + Date + " " + Heure + "')";
            this.st.executeUpdate(Insert);
            fermeture();
            JOptionPane.showMessageDialog(null, "Retrait effectuer");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pas de retrait " + e);
        }
    }
    //La facture

}
