package win;

/**
 * @author Moses
 */
public class charge extends javax.swing.JFrame {

    /**
     * Creates new form charge
     */
    public charge() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        desk = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout deskLayout = new javax.swing.GroupLayout(desk);
        desk.setLayout(deskLayout);
        deskLayout.setHorizontalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        deskLayout.setVerticalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desk)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desk)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 90, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moses\\Desktop\\ch.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws Exception{
    charge jo = new charge();
    jo.setVisible(true);
    chun un = new chun();
    chdeux deux = new chdeux();
    chtrois trs = new chtrois();
    chqut qt = new chqut();
    chcinq cq = new chcinq();
    chsix sx = new chsix();
    chsep sp = new chsep();
    chht ht = new chht();
    chne ne = new chne();
    chdi di = new chdi();
    chon on = new chon();
    chdou dou = new chdou();
    for (int i = 0; i <= 100; i++) {
            Thread.sleep(70);
            switch (i) {
                case 1:
                    jo.desk.add(un).setVisible(true);
                    break;
                case 2:
                    jo.desk.add(deux).setVisible(true);
                    break;
                case 3:
                    jo.desk.add(trs).setVisible(true);
                    break;
                case 4:
                    jo.desk.add(qt).setVisible(true);
                    break;
                case 5:
                    jo.desk.add(cq).setVisible(true);
                    break;
                case 6:
                    jo.desk.add(sx).setVisible(true);
                    break;
                case 7:
                    jo.desk.add(sp).setVisible(true);
                    break;
                case 8:
                    jo.desk.add(ht).setVisible(true);
                    break;
                case 9:
                    jo.desk.add(ne).setVisible(true);
                    break;
                case 10:
                    jo.desk.add(di).setVisible(true);
                    break;
                case 11:
                    jo.desk.add(on).setVisible(true);
                    break;
                case 12:
                    jo.desk.add(dou).setVisible(true);
                    break;
                case 13:
                    jo.desk.removeAll();
                    jo.desk.add(un).setVisible(true);
                    break;
                case 14:
                    jo.desk.removeAll();
                    jo.desk.add(deux).setVisible(true);
                    break;
                case 15:
                    jo.desk.removeAll();
                    jo.desk.add(trs).setVisible(true);
                    break;
                case 16:
                    jo.desk.removeAll();
                    jo.desk.add(qt).setVisible(true);
                    break;
                case 17:
                    jo.desk.removeAll();
                    jo.desk.add(cq).setVisible(true);
                    break;
                case 18:
                    jo.desk.removeAll();
                    jo.desk.add(sx).setVisible(true);
                    break;
                case 19:
                    jo.desk.removeAll();
                    jo.desk.add(sp).setVisible(true);
                    break;
                case 20:
                    jo.desk.removeAll();
                    jo.desk.add(ht).setVisible(true);
                    break;
                case 21:
                    jo.desk.removeAll();
                    jo.desk.add(ne).setVisible(true);
                    break;
                case 22:
                    jo.desk.removeAll();
                    jo.desk.add(di).setVisible(true);
                    break;
                case 23:
                    jo.desk.removeAll();
                    jo.desk.add(on).setVisible(true);
                    break;
                case 24:
                    jo.desk.removeAll();
                    jo.desk.add(dou).setVisible(true);
                    break;
                case 25:
                    jo.desk.removeAll();
                    jo.desk.add(un).setVisible(true);
                    break;
                case 26:
                    jo.desk.removeAll();
                    jo.desk.add(deux).setVisible(true);
                    break;
                case 27:
                    jo.desk.removeAll();
                    jo.desk.add(trs).setVisible(true);
                    break;
                case 28:
                    jo.desk.removeAll();
                    jo.desk.add(qt).setVisible(true);
                    break;
                case 29:
                    jo.desk.removeAll();
                    jo.desk.add(cq).setVisible(true);
                    break;
                case 30:
                    jo.desk.removeAll();
                    jo.desk.add(sx).setVisible(true);
                    break;
                case 31:
                    jo.desk.removeAll();
                    jo.desk.add(sp).setVisible(true);
                    break;
                case 32:
                    jo.desk.removeAll();
                    jo.desk.add(ht).setVisible(true);
                    break;
                case 33:
                    jo.desk.removeAll();
                    jo.desk.add(ne).setVisible(true);
                    break;
                case 34:
                    jo.desk.removeAll();
                    jo.desk.add(di).setVisible(true);
                    break;
                case 35:
                    jo.desk.removeAll();
                    jo.desk.add(on).setVisible(true);
                    break;
                case 36:
                    jo.desk.removeAll();
                    jo.desk.add(dou).setVisible(true);
                    break;
                case 37:
                    jo.desk.removeAll();
                    jo.desk.add(un).setVisible(true);
                    break;
                case 38:
                    jo.desk.removeAll();
                    jo.desk.add(deux).setVisible(true);
                    break;
                case 39:
                    jo.desk.removeAll();
                    jo.desk.add(trs).setVisible(true);
                    break;
                case 40:
                    jo.desk.removeAll();
                    jo.desk.add(qt).setVisible(true);
                    break;
                case 41:
                    jo.desk.removeAll();
                    jo.desk.add(cq).setVisible(true);
                    break;
                case 42:
                    jo.desk.removeAll();
                    jo.desk.add(sx).setVisible(true);
                    break;
                case 43:
                    jo.desk.removeAll();
                    jo.desk.add(sp).setVisible(true);
                    break;
                case 44:
                    jo.desk.removeAll();
                    jo.desk.add(ht).setVisible(true);
                    break;
                case 45:
                    jo.desk.removeAll();
                    jo.desk.add(ne).setVisible(true);
                    break;
                case 46:
                    jo.desk.removeAll();
                    jo.desk.add(di).setVisible(true);
                    break;
                case 47:
                    jo.desk.removeAll();
                    jo.desk.add(on).setVisible(true);
                    break;
                case 48:
                   jo.desk.removeAll();
                    jo.desk.add(dou).setVisible(true);
                    break;
                case 49:
                    jo.desk.removeAll();
                    jo.desk.add(un).setVisible(true);
                    break;
                case 50:
                    jo.desk.removeAll();
                    jo.desk.add(deux).setVisible(true);
                    break;
                case 51:
                    jo.desk.removeAll();
                    jo.desk.add(trs).setVisible(true);
                    break;
                case 52:
                    jo.desk.removeAll();
                    jo.desk.add(deux).setVisible(true);
                    break;
                case 53:
                    jo.desk.removeAll();
                    jo.desk.add(trs).setVisible(true);
                    break;
                case 54:
                    jo.desk.removeAll();
                    jo.desk.add(qt).setVisible(true);
                    break;
                case 55:
                    jo.desk.removeAll();
                    jo.desk.add(cq).setVisible(true);
                    break;
                case 56:
                    jo.desk.removeAll();
                    jo.desk.add(sx).setVisible(true);
                    break;
                case 57:
                    jo.desk.removeAll();
                    jo.desk.add(sp).setVisible(true);
                    break;
                case 58:
                    jo.desk.removeAll();
                    jo.desk.add(ht).setVisible(true);
                    break;
                case 59:
                    jo.desk.removeAll();
                    jo.desk.add(ne).setVisible(true);
                    break;
                case 60:
                    jo.desk.removeAll();
                    jo.desk.add(di).setVisible(true);
                    break;
                case 61:
                    jo.desk.removeAll();
                    jo.desk.add(on).setVisible(true);
                    break;
                case 62:
                    jo.desk.removeAll();
                    jo.desk.add(dou).setVisible(true);
                    break;
                case 63:
                    jo.desk.removeAll();
                    jo.desk.add(un).setVisible(true);
                    break;
                case 64:
                    jo.desk.removeAll();
                    jo.desk.add(deux).setVisible(true);
                    break;
                case 65:
                    jo.desk.removeAll();
                    jo.desk.add(trs).setVisible(true);
                    break;
                case 66:
                    jo.desk.removeAll();
                    jo.desk.add(qt).setVisible(true);
                    break;
                case 67:
                    jo.desk.removeAll();
                    jo.desk.add(cq).setVisible(true);
                    break;
                case 68:
                    jo.desk.removeAll();
                    jo.desk.add(sx).setVisible(true);
                    break;
                case 69:
                    jo.desk.removeAll();
                    jo.desk.add(sp).setVisible(true);
                    break;
                case 70:
                    jo.desk.removeAll();
                    jo.desk.add(ht).setVisible(true);
                    break;
                case 71:
                    jo.desk.removeAll();
                    jo.desk.add(ne).setVisible(true);
                    break;
                case 72:
                    jo.desk.removeAll();
                    jo.desk.add(di).setVisible(true);
                    break;
                case 73:
                    jo.desk.removeAll();
                    jo.desk.add(on).setVisible(true);
                    break;
                case 74:
                    jo.desk.removeAll();
                    jo.desk.add(dou).setVisible(true);
                    break;
                case 75:
                    jo.desk.removeAll();
                    jo.desk.add(un).setVisible(true);
                    break;
                case 76:
                    jo.desk.removeAll();
                    jo.desk.add(deux).setVisible(true);
                    break;
                case 77:
                    jo.desk.removeAll();
                    jo.desk.add(trs).setVisible(true);
                    break;
                case 78:
                    jo.desk.removeAll();
                    jo.desk.add(qt).setVisible(true);
                    break;
                case 79:
                    jo.desk.removeAll();
                    jo.desk.add(cq).setVisible(true);
                    break;
                case 80:
                    jo.desk.removeAll();
                    jo.desk.add(sx).setVisible(true);
                    break;
                case 81:
                    jo.desk.removeAll();
                    jo.desk.add(sp).setVisible(true);
                    break;
                case 82:
                    jo.desk.removeAll();
                    jo.desk.add(ht).setVisible(true);
                    break;
                case 83:
                    jo.desk.removeAll();
                    jo.desk.add(ne).setVisible(true);
                    break;
                case 84:
                    jo.desk.removeAll();
                    jo.desk.add(di).setVisible(true);
                    break;
                case 85:
                    jo.desk.removeAll();
                    jo.desk.add(on).setVisible(true);
                    break;
                case 86:
                    jo.desk.removeAll();
                    jo.desk.add(dou).setVisible(true);
                    break;
                case 87:
                    jo.desk.removeAll();
                    jo.desk.add(un).setVisible(true);
                    break;
                case 88:
                    jo.desk.removeAll();
                    jo.desk.add(deux).setVisible(true);
                    break;
                case 89:
                    jo.desk.removeAll();
                    jo.desk.add(trs).setVisible(true);
                    break;
                case 90:
                    jo.desk.removeAll();
                    jo.desk.add(qt).setVisible(true);
                    break;
                case 91:
                    jo.desk.removeAll();
                    jo.desk.add(cq).setVisible(true);
                    break;
                case 92:
                    jo.desk.removeAll();
                    jo.desk.add(sx).setVisible(true);
                    break;
                case 93:
                    jo.desk.removeAll();
                    jo.desk.add(sp).setVisible(true);
                    break;
                case 94:
                    jo.desk.removeAll();
                    jo.desk.add(ht).setVisible(true);
                    break;
                case 95:
                    jo.desk.removeAll();
                    jo.desk.add(ne).setVisible(true);
                    break;
                case 96:
                    jo.desk.removeAll();
                    jo.desk.add(di).setVisible(true);
                    break;
                case 97:
                    jo.desk.removeAll();
                    jo.desk.add(on).setVisible(true);
                    break;
                case 98:
                   jo.desk.removeAll();
                    jo.desk.add(dou).setVisible(true);
                    break;
                case 99:
                    jo.desk.removeAll();
                    jo.desk.add(un).setVisible(true);
                    break;
                case 100:
                    jo.desk.removeAll();
                    jo.desk.add(deux).setVisible(true);
                    break;
                default:
                    break;
                    
            }
        }
    jo.desk.setVisible(false);
    jo.dispose();
    new att().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desk;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
