/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestioncaisse;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author moise
 */
public class operation extends javax.swing.JFrame {
     Double Depot=0.0;
    Double Retrait=0.0;
    Double bHeight=0.0;
    ArrayList<String> No= new ArrayList<>();
    ArrayList<String> Post= new ArrayList<>();
    ArrayList<String> Pre= new ArrayList<>();
    ArrayList<String> Date1= new ArrayList<>();
    ArrayList<String> Mont= new ArrayList<>();
// Base de donnee
  private String url="jdbc:mysql://127.0.0.1:3306/base",user="root",pass="";
  private Statement st;
  private String requetteVerifier;
  private String requetteAide;
  private String requetteEnregisBilan;
  private String requetteInserer;
  private Connection con;
  private String devise; 
  private String rech;
  void ouverture(){
      try {
          Class.forName("com.mysql.jdbc.Driver");
          this.con=(Connection)DriverManager.getConnection(url,user,pass);
          System.out.println("c'est bon");
      } catch (Exception e) {JOptionPane.showMessageDialog(null,""+e.getMessage());
      }
  }
  void fermeture(){
      try {
          this.con.close();
          this.st.close();
          System.out.println("ferme");
      } catch (Exception e) {JOptionPane.showMessageDialog(null,""+e.getMessage());
      }
}

    /**
     * Creates new form operation
     */
    public operation() {
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        choixOperation = new javax.swing.JComboBox();
        choixDevise = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        mdp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pre = new javax.swing.JTextField();
        post = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        boxMontantActuelDollar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        boxMontantActuelFC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        montantInserer = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        sav8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Opperation");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel11)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel1.setText("Operation");

        jLabel2.setText("Devise");

        choixOperation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DEPOT", "RETRAIT" }));
        choixOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixOperationActionPerformed(evt);
            }
        });

        choixDevise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FC", "$" }));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Info sur client"));

        mdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdpActionPerformed(evt);
            }
        });

        jLabel3.setText("Nom");

        jLabel5.setText("Prenom");

        jLabel4.setText("Post-Nom");

        jLabel6.setText("Mot de passe");

        jToggleButton1.setText("Verifier");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(post, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(pre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mdp, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nom)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Montant Actuel"));

        boxMontantActuelDollar.setEditable(false);
        boxMontantActuelDollar.setText("0");

        jLabel8.setText("$");

        jLabel7.setText("FC");

        boxMontantActuelFC.setEditable(false);
        boxMontantActuelFC.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boxMontantActuelFC)
                    .addComponent(boxMontantActuelDollar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(boxMontantActuelFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(boxMontantActuelDollar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel9.setText("Inserer le montant");

        jLabel10.setText("Total");

        total.setEditable(false);

        jButton1.setText("Effectuer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        sav8.setText("jLabel12");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(montantInserer)
                                    .addComponent(total))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(choixOperation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(choixDevise, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sav8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(281, 281, 281))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(choixOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sav8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(choixDevise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(montantInserer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choixOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choixOperationActionPerformed

    private void mdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mdpActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Accueil().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            String op=(String) choixOperation.getSelectedItem();
  //------------------------ DEPOT DEPOT DEPOT  --------------------------------------------------------------------------
if(op=="Depot"){
String dev=(String) choixDevise.getSelectedItem();
if(dev.equals("FC")){
 // recuperation du montant actuel dollar
    int h=Integer.parseInt(boxMontantActuelFC.getText());
    // recuperation montant inserer
    int fg=Integer.parseInt(montantInserer.getText());
    // addition 
    int jk=h+fg;
     if((jk>0) && (fg>0)){
    // affichage du montant total
    total.setText(""+jk);
    // recuperation du montant total
    int g= Integer.parseInt(total.getText());
    JOptionPane.showConfirmDialog(null, " nouveau montant : "+g+" poursuivre ?");
     final SimpleDateFormat sdf= new SimpleDateFormat("dd-MM-yyyy  hh:mm:ss");
        final String datestr=sdf.format(new Date ());
        String motif="Depot";
         DepotFranc(nom.getText(),post.getText(),pre.getText(), datestr,fg,motif, g);
    EnregistrementBilan(sav8.getText(),g);
     JOptionPane.showMessageDialog(null," Operation effectuee");
      No.add(nom.getText());
      Post.add(post.getText());
      Pre.add(pre.getText());
      Date1.add(datestr);
      Mont.add(""+g);
       EnregistrementBilan2(datestr, g);
       JOptionPane.showConfirmDialog(null," Imprimer ?");
      Impri();
     }
      else{JOptionPane.showMessageDialog(null," Solde insuffisant");
      montantInserer.setText("");
      
      }
}
if(dev.equals("$")){
    // recuperation du montant actuel dollar
    int h=Integer.parseInt(boxMontantActuelDollar.getText());
    // recuperation montant inserer
    int fg=Integer.parseInt(montantInserer.getText());
    // addition 
    int jk=h+fg;
     if((jk>0) && (fg>0)){
    // affichage du montant total
    total.setText(""+jk);
    // recuperation du montant total
    int g= Integer.parseInt(total.getText());
    JOptionPane.showConfirmDialog(null, " nouveau montant : "+g+" poursuivre ?");
     final SimpleDateFormat sdf= new SimpleDateFormat("dd-MM-yyyy  hh:mm:ss");
        final String datestr=sdf.format(new Date ());
        String motif="Depot";
    DepotDollar(nom.getText(),post.getText(),pre.getText(), datestr,fg,motif, g);
    EnregistrementBilan(sav8.getText(),g);
      JOptionPane.showMessageDialog(null," Operation effectuee");
      No.add(nom.getText());
      Post.add(post.getText());
      Pre.add(pre.getText());
      Date1.add(datestr);
      Mont.add(""+g);
       EnregistrementBilan(datestr, g);
      Impri();
     }
      else{JOptionPane.showMessageDialog(null," Solde insuffisant");
      montantInserer.setText("");
      }
   }
}
//------------------------------------------------- RETRAIT RETRAIT RETRAIT  --------------------------------------------------------------------------
if(op=="Retrait"){
String dev=(String) choixDevise.getSelectedItem();
if(dev.equals("FC")){
  // recuperation du montant actuel dollar
    int h=Integer.parseInt(boxMontantActuelFC.getText());
// recuperation montant inserer
    int fg=Integer.parseInt(montantInserer.getText());
    // soustraction
      int jk=h-fg;
      if((jk>0) && (fg>0)){
       // affichage du montant total
    total.setText(""+jk);
    
    int g= Integer.parseInt(total.getText());
    JOptionPane.showConfirmDialog(null, " nouveau montant : "+g+" poursuivre ?");final SimpleDateFormat sdf= new SimpleDateFormat("dd-MM-yyyy  hh:mm:ss");
        final String datestr=sdf.format(new Date ());
        String motif="Retrait";
    RetraitFranc(nom.getText(),post.getText(),pre.getText(), datestr,fg,motif, g);
    EnregistrementBilan(sav8.getText(),g);
       JOptionPane.showMessageDialog(null," Operation effectuee");
       No.add(nom.getText());
      Post.add(post.getText());
      Pre.add(pre.getText());
      Date1.add(datestr);
      Mont.add(""+g);
       EnregistrementBilan2(datestr, g);
       Impri();
      }
      else{JOptionPane.showMessageDialog(null," Solde insuffisant");
      montantInserer.setText("");
      }
}
if(dev.equals("$")){
     // recuperation du montant actuel dollar
    int h=Integer.parseInt(boxMontantActuelDollar.getText());
// recuperation montant inserer
    int fg=Integer.parseInt(montantInserer.getText());
    // soustraction
      int jk=h-fg;
      if((jk>0) && (fg>0)){
       // affichage du montant total
    total.setText(""+jk);
    int g= Integer.parseInt(total.getText());
    JOptionPane.showConfirmDialog(null, " nouveau montant : "+g+" poursuivre ?");final SimpleDateFormat sdf= new SimpleDateFormat("dd-MM-yyyy  hh:mm:ss");
        final String datestr=sdf.format(new Date ());
        String motif="Retrait";
    RetraitDollar(nom.getText(),post.getText(),pre.getText(), datestr,fg,motif, g);
    EnregistrementBilan(sav8.getText(),g);
       JOptionPane.showMessageDialog(null," Operation effectuee"); montantInserer.setText("");
      No.add(nom.getText());
      Post.add(post.getText());
      Pre.add(pre.getText());
      Date1.add(datestr);
      Mont.add(""+g);
          EnregistrementBilan(datestr, g);
      Impri();
      }
      else{JOptionPane.showMessageDialog(null," Solde insuffisant");
             
      }  
}
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jButton1MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
          Recherche(nom.getText(),post.getText(),pre.getText(),mdp.getText());
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new operation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxMontantActuelDollar;
    private javax.swing.JTextField boxMontantActuelFC;
    private javax.swing.JComboBox choixDevise;
    private javax.swing.JComboBox choixOperation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField mdp;
    private javax.swing.JTextField montantInserer;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField post;
    private javax.swing.JTextField pre;
    private javax.swing.JLabel sav8;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
public void DepotFranc(String Nom,String Postnom,String Prenom, String Date, int Montant, String Motif,int MontantTotal){
    try {
        ouverture();
    this.st=(Statement)this.con.createStatement();
    this.requetteInserer="insert into franc value('"+Nom+"','"+Postnom+"','"+Prenom+"','"+Date+"','"+Montant+"','"+Motif+"','"+MontantTotal+"')";
    this.st.executeUpdate(requetteInserer);
        System.out.println("c'est bon");
        fermeture();
    } catch (Exception e) {JOptionPane.showMessageDialog(null,"erreur "+e.getMessage());
    }
}

public void DepotDollar(String Nom,String Postnom,String Prenom, String Date, int Montant, String Motif,int MontantTotal){
    try {ouverture();
    this.st=(Statement)this.con.createStatement();
    this.requetteInserer="insert into dollar value('"+Nom+"','"+Postnom+"','"+Prenom+"','"+Date+"','"+Montant+"','"+Motif+"','"+MontantTotal+"')";
    this.st.executeUpdate(requetteInserer);
        System.out.println("c'est bon");
        fermeture();
    } catch (SQLException e) {JOptionPane.showMessageDialog(null,"erreur "+e.getMessage());
    }
}


public void EnregistrementBilan(String Date,int Montant){
    try {ouverture();
    this.st=(Statement)this.con.createStatement();
    this.requetteEnregisBilan="insert into Bilan value('"+Date+"','"+Montant+"')";
    this.st.executeUpdate(requetteEnregisBilan);
        System.out.println("c'est ok");
         fermeture();
    } catch (Exception e) {JOptionPane.showMessageDialog(null,""+e.getMessage());
    }
}

public void EnregistrementBilan2(String Date,int Montant2){
    try {ouverture();
    this.st=(Statement)this.con.createStatement();
    this.requetteEnregisBilan="insert into Bilan2 value('"+Date+"','"+Montant2+"')";
    this.st.executeUpdate(requetteEnregisBilan);
        System.out.println("c'est ok");
         fermeture();
    } catch (Exception e) {JOptionPane.showMessageDialog(null,""+e.getMessage());
    }
}

public void RetraitFranc(String Nom,String Postnom,String Prenom, String Date, int Montant, String Motif,int MontantTotal){
    try {
        ouverture();
    this.st=(Statement)this.con.createStatement();
    this.requetteInserer="insert into franc value('"+Nom+"','"+Postnom+"','"+Prenom+"','"+Date+"','"+Montant+"','"+Motif+"','"+MontantTotal+"')";
    this.st.executeUpdate(requetteInserer);
        System.out.println("c'est ok");
        fermeture();
    } catch (Exception e) {JOptionPane.showMessageDialog(null,"erreur "+e.getMessage());
    }
    
}

public void RetraitDollar(String Nom,String Postnom,String Prenom, String Date, int Montant, String Motif,int MontantTotal){
    try {ouverture();
    this.st=(Statement)this.con.createStatement();
    this.requetteInserer="insert into dollar value('"+Nom+"','"+Postnom+"','"+Prenom+"','"+Date+"','"+Montant+"','"+Motif+"','"+MontantTotal+"')";
    this.st.executeUpdate(requetteInserer);
        System.out.println("c'est ok");
        fermeture();
        
    } catch (Exception e) {JOptionPane.showMessageDialog(null,"erreur "+e.getMessage());
    }
}

public void Recherche(String Nom, String Postnom, String Prenom, String MOTDEPASSE){
    try {
        ouverture();
        this.st=(Statement)this.con.createStatement();
        this.requetteVerifier="select * from client where Nom='"+Nom+"' and Postnom ='"+Postnom+"'  and Prenom ='"+Prenom+"'  and MOTDEPASSE ='"+MOTDEPASSE+"'";
        ResultSet rs= this.st.executeQuery(requetteVerifier);
        if(rs.next()){
            RechercheDollar(Nom, Postnom, Prenom);
            RechercheFranc(Nom, Postnom, Prenom);
        
        }
        fermeture();
    } catch (Exception e) {JOptionPane.showMessageDialog(null,""+e.getMessage());
    }
}

public void RechercheDollar(String Nom, String Postnom,String Prenom){
    try {
        ouverture();
        this.st=(Statement)this.con.createStatement();
        this.rech="select MontantTotal from dollar where Nom='"+Nom+"' and Postnom='"+Postnom+"' and prenom='"+Prenom+"' ";
        ResultSet rs=st.executeQuery(rech);
        while(rs.next())   
        {int mm=rs.getInt("MontantTotal");
        boxMontantActuelDollar.setText(""+mm);
        }
        fermeture();
    } catch (Exception e) {JOptionPane.showMessageDialog(null,"erreur "+e.getMessage());
    }
}

 public void RechercheFranc(String Nom, String Postnom,String Prenom){
    try {
        ouverture();
        this.st=(Statement)this.con.createStatement();
        this.rech="select MontantTotal from franc where Nom='"+Nom+"' and Postnom='"+Postnom+"' and Prenom='"+Prenom+"' ";
        ResultSet rs=st.executeQuery(rech);
        while(rs.next())   
        {int mm=rs.getInt("MontantTotal");
        boxMontantActuelFC.setText(""+mm);
            System.out.println("c'est bon");
        }
        fermeture();
    } catch (SQLException e) {JOptionPane.showMessageDialog(null,"erreur "+e.getMessage());
    }
}
 
 public PageFormat getPageFormat(PrinterJob pj){

    PageFormat pf=pj.defaultPage();
    Paper paper= pf.getPaper();
    
    double bodyHeight= bHeight;
    double headerHeight = 5.0;
    double footerHeight = 5.0;
    double width= cm_to_pp(8);
    double height= cm_to_pp(headerHeight+bodyHeight+footerHeight);
    paper.setSize(width,height);
    pf.setPaper(paper);
return pf;
}
protected static double cm_to_pp(double cm){
return toPPI(cm*0.393600787);
}
protected static double toPPI(double inch){
return inch * 72d;
}
public class BillPrintale implements Printable{
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException{
    int result=NO_SUCH_PAGE;
    if(pageIndex==0){
    Graphics2D  g2d= (Graphics2D) graphics;
    double width= pageFormat.getImageableHeight();
    g2d.translate((int)pageFormat.getImageableX(),(int) pageFormat.getImageableX());
        try {
            int y=20;
            int yShift=10;
            int headerRectHeight=15;
            g2d.setFont(new Font("Monospaced",Font.PLAIN,9));
              //  g2d.drawImage(icon.getImage(), 50, 20, 90 , 30, rootPane);y+=yShift+30;
                g2d.drawString("---------------------------------------",12,y);y+=yShift;
                g2d.drawString("         Caisse G5 PROGS            ",12,y);y+=yShift;
                g2d.drawString("    No 00000 Adresse line one   ",12,y);y+=yShift;
                g2d.drawString("Adresse: C/limete Av/mobutu No-01   ",12,y);y+=yShift;
                g2d.drawString("    www.Facebook.com/G5 Progs    ",12,y);y+=yShift;
                g2d.drawString("         +243821712363      ",12,y);y+=yShift;
                g2d.drawString("---------------------------------------",12,y);y+=headerRectHeight;
                g2d.drawString("  NOM DU CLIENT + OPERATION ",10,y);y+=yShift;
                g2d.drawString("---------------------------------------",10,y);y+=headerRectHeight;           
                g2d.drawString("   "+No+"      ",10,y);y+=yShift;
                g2d.drawString("   "+Post+"     ",10,y);y+=yShift;
                g2d.drawString("   "+Pre+"      ",10,y);y+=yShift;
                g2d.drawString("---------------------------------------",10,y);y+=yShift;
              //  g2d.drawString("DEPOT EN CAISSE:       "+.getText()+"    ",10,y);y+=yShift;
                g2d.drawString("---------------------------------------",10,y);y+=yShift;
              //  g2d.drawString("RETRAIT EN CAISSE:     "+retrait.getText()+"    ",10,y);y+=yShift;
                g2d.drawString("---------------------------------------",10,y);y+=yShift;
                g2d.drawString("        LA CAISSE G5      ",10,y);y+=yShift;
                g2d.drawString("---------------------------------------",10,y);y+=yShift;
                g2d.drawString("   DEVELLOPED BY G5 PROGS   ",10,y);y+=yShift;
                g2d.drawString("   I WILL REALIZE MY DREAM    ",10,y);y+=yShift; 
            
            
            
            
            
        } catch (Exception e) { e.printStackTrace();
        }
    result=PAGE_EXISTS;
    
    
    }
    return result;
    }
    
    
    
}
public void Impri(){
bHeight= Double.valueOf(No.size());
JOptionPane.showMessageDialog(rootPane,bHeight);
PrinterJob pj=PrinterJob.getPrinterJob();
pj.setPrintable(new BillPrintale(),getPageFormat(pj));
    try {
        pj.print();
    } catch (Exception e) { e.printStackTrace();
    }
}     
}
