/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maxtech;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class N_utilisateur extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    /**
     * Creates new form N_utilisateur
     */
    public N_utilisateur() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
     public void connecter(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=(Connection)(com.mysql.jdbc.Connection)DriverManager.getConnection("jdbc:mysql://localhost/maxtech","root","");
            //JOptionPane.showMessageDialog(null,"Connection reussie");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        VNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        VConnex = new javax.swing.JButton();
        VAnnul = new javax.swing.JButton();
        VNouvP = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        VEmail = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        VPass = new javax.swing.JPasswordField();
        VCPass = new javax.swing.JPasswordField();
        BVoir = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_add_user_male_120px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Profil");

        jPanel2.setBackground(new java.awt.Color(33, 32, 35));

        jLabel2.setBackground(new java.awt.Color(240, 151, 57));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Nom d'utilisateur");

        jSeparator1.setBackground(new java.awt.Color(0, 204, 204));

        VNom.setBackground(new java.awt.Color(33, 32, 35));
        VNom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        VNom.setForeground(new java.awt.Color(255, 255, 255));
        VNom.setToolTipText("");
        VNom.setBorder(null);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        VConnex.setBackground(new java.awt.Color(0, 204, 204));
        VConnex.setText("Inscription");
        VConnex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VConnexActionPerformed(evt);
            }
        });

        VAnnul.setBackground(new java.awt.Color(255, 0, 0));
        VAnnul.setText("Annuler");
        VAnnul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VAnnulActionPerformed(evt);
            }
        });

        VNouvP.setBackground(new java.awt.Color(33, 32, 35));
        VNouvP.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        VNouvP.setForeground(new java.awt.Color(204, 204, 204));
        VNouvP.setText("Vous avez déjà un compte? clickez ici pour vous connecter");
        VNouvP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VNouvP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VNouvPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VNouvPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VNouvPMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Votre email");

        VEmail.setBackground(new java.awt.Color(33, 32, 35));
        VEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        VEmail.setForeground(new java.awt.Color(255, 255, 255));
        VEmail.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("Confirmer le Mots de passe");

        jSeparator3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("Mots de passe");

        jSeparator4.setBackground(new java.awt.Color(0, 204, 204));

        VPass.setBackground(new java.awt.Color(33, 32, 35));
        VPass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        VPass.setForeground(new java.awt.Color(255, 255, 255));
        VPass.setBorder(null);

        VCPass.setBackground(new java.awt.Color(33, 32, 35));
        VCPass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        VCPass.setForeground(new java.awt.Color(255, 255, 255));
        VCPass.setBorder(null);

        BVoir.setBackground(new java.awt.Color(33, 32, 35));
        BVoir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BVoir.setForeground(new java.awt.Color(240, 151, 57));
        BVoir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BVoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_eye_15px.png"))); // NOI18N
        BVoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVoirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 132, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VNouvP)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(77, 77, 77))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(VCPass, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VPass, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VNom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BVoir)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VConnex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VAnnul, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VNom, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VPass, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(VCPass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BVoir))
                .addGap(8, 8, 8)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VAnnul)
                    .addComponent(VConnex))
                .addGap(28, 28, 28)
                .addComponent(VNouvP)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void VConnexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VConnexActionPerformed
        try {
            String nom = VNom.getText();
            String email = VEmail.getText();
            String pass = VPass.getText();
            String cpass = VCPass.getText();
            if (nom.isEmpty() || email.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Erreur de Saisi", null, JOptionPane.ERROR_MESSAGE);
                VNom.setText(null);
                VEmail.setText(null);
                VPass.setText(null);
                VCPass.setText(null);
            } else if (pass.isEmpty() || cpass.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Erreur de Saisi", null, JOptionPane.ERROR_MESSAGE);
                VNom.setText(null);
                VEmail.setText(null);
                VPass.setText(null);
                VCPass.setText(null);
            } else {
                if (cpass.equals(pass)) {
                    try {
                         connecter();
            pst= (PreparedStatement) con.prepareStatement("DELETE FROM `ventes` WHERE 1");
            pst= (PreparedStatement) con.prepareStatement("DELETE FROM `user` WHERE 1");  
            pst= (PreparedStatement) con.prepareStatement("insert user(nom, motdepasse) values(?,?)");
            pst.setString(1,VNom.getText());
            pst.setString(2,VPass.getText());
            pst.executeUpdate();
            con.close();
            con.close();
                    } catch (Exception e) {
                        System.out.println("erreur "+e);
                    }
    
                    menu m = new menu();
                    m.setVisible(true);
                    m.setLocationRelativeTo(null);
                    m.setResizable(true);
                    this.setExtendedState(MAXIMIZED_BOTH);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(null, "Erreur de code", null, JOptionPane.ERROR_MESSAGE);

                    VPass.setText(null);
                    VCPass.setText(null);
                }

            }
        } catch (Exception e) {
            System.out.println("erreur "+e);

        }
    }//GEN-LAST:event_VConnexActionPerformed

    private void VAnnulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VAnnulActionPerformed
        VNom.setText(null);
        VEmail.setText(null);
        VPass.setText(null);
        VCPass.setText(null);
    }//GEN-LAST:event_VAnnulActionPerformed

    private void VNouvPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VNouvPMouseClicked
        utilisateur u = new utilisateur();
        u.setVisible(true);
        u.setLocationRelativeTo(null);
        u.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_VNouvPMouseClicked

    private void VNouvPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VNouvPMouseEntered
        VNouvP.setForeground(new Color(240, 151, 57));
        VNouvP.setOpaque(true);
    }//GEN-LAST:event_VNouvPMouseEntered

    private void VNouvPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VNouvPMouseExited
        VNouvP.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_VNouvPMouseExited

    private void BVoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVoirActionPerformed
        if (BVoir.isSelected()) {
            VPass.setEchoChar((char) 0);
            VCPass.setEchoChar((char) 0);
        } else {
            VPass.setEchoChar('•');
            VCPass.setEchoChar('•');
        }
    }//GEN-LAST:event_BVoirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(N_utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(N_utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(N_utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(N_utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new N_utilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BVoir;
    private javax.swing.JButton VAnnul;
    private javax.swing.JPasswordField VCPass;
    private javax.swing.JButton VConnex;
    private javax.swing.JTextField VEmail;
    private javax.swing.JTextField VNom;
    private javax.swing.JLabel VNouvP;
    private javax.swing.JPasswordField VPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
