/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package macaisse1;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Anne
 */
public class AjoutClient extends javax.swing.JFrame {
  private String url="jdbc:mysql://127.0.0.1:3306/Base",user="root",pass="";
  private Statement st;
  private String requetteVerifier;
  private String requetteAide;
  private String requetteEnregisBilan;
  private String requetteInserer;
  private Connection con;
  private String devise;
  private String rech;
  void ouverture(){
      try {
          Class.forName("com.mysql.jdbc.Driver");
          this.con=(Connection)DriverManager.getConnection(url,user,pass);
          System.out.println("c'est bon");
      } catch (Exception e) {JOptionPane.showMessageDialog(null,""+e.getMessage());
      }
  }
  void fermeture(){
      try { 
          this.con.close();
          this.st.close();
          System.out.println("ferme");
      } catch (Exception e) {JOptionPane.showMessageDialog(null,""+e.getMessage());
      }
}
  
    /**
     * Creates new form AjoutClient
     */
    public AjoutClient() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setResizable(rootPaneCheckingEnabled);                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boxNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        boxPostnom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        boxPrenom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        boxCode = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        boxAdresse = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        boxNumeroTel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        boxDate = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 107, -1, -1));
        jPanel1.add(boxNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 99, 92, 31));

        jLabel2.setText("Post-nom");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 148, -1, -1));
        jPanel1.add(boxPostnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 141, 92, 29));

        jLabel3.setText("Prenom");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 176, -1, -1));
        jPanel1.add(boxPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 176, 93, 28));

        jLabel4.setText("Code");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 229, -1, -1));
        jPanel1.add(boxCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 222, 93, 29));

        jLabel9.setText("Adresse");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 269, -1, -1));
        jPanel1.add(boxAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 262, 137, 29));

        jLabel10.setText("Numero Tel");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 311, -1, -1));

        boxNumeroTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNumeroTelActionPerformed(evt);
            }
        });
        jPanel1.add(boxNumeroTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 302, 96, 32));

        jButton1.setText("Accueil");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        boxDate.setText("Date");
        jPanel1.add(boxDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 55, -1, -1));

        jLabel14.setText("Quit");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 0, 68, 49));

        jButton2.setText("Effectuer");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 345, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new ABC().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
dispose();       
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      final SimpleDateFormat sdf= new SimpleDateFormat("dd-MM-yyyy  hh:mm:ss");
        final String datestr=sdf.format(new Date ());
        boxDate.setText(datestr);
        String motif="ENREGISTREMENT";
        int NumeroTel=Integer.parseInt(boxNumeroTel.getText());
        Entrer(boxNom.getText(),boxPostnom.getText(),boxPrenom.getText(),boxCode.getText(),boxAdresse.getText(),NumeroTel ,boxDate.getText());
        EntrerDollar(boxNom.getText(),boxPostnom.getText(),boxPrenom.getText(), boxDate.getText(),0 , motif, 0);
        EntrerFranc(boxNom.getText(),boxPostnom.getText(),boxPrenom.getText(),boxDate.getText(), 0, motif, 0); 
        dispose();
        new ABC().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void boxNumeroTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNumeroTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNumeroTelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxAdresse;
    private javax.swing.JPasswordField boxCode;
    private javax.swing.JLabel boxDate;
    private javax.swing.JTextField boxNom;
    private javax.swing.JTextField boxNumeroTel;
    private javax.swing.JTextField boxPostnom;
    private javax.swing.JTextField boxPrenom;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
public void Entrer(String Nom,String Postnom,String Prenom,String Code,String Adresse, int NumeroTel,String Date){
    try {
        ouverture();
    this.st=(Statement)this.con.createStatement();
this.requetteInserer="insert into client value('"+Nom+"','"+Postnom+"','"+Prenom+"','"+Code+"','"+Adresse+"','"+NumeroTel+"','"+Date+"')";
    this.st.executeUpdate(requetteInserer);
        JOptionPane.showMessageDialog(null," Enregistrer");
        fermeture();
    } catch (Exception e) {JOptionPane.showMessageDialog(null,"erreur \n "+e.getMessage());
    }
}
public void EntrerDollar(String Nom,String Postnom,String Prenom, String Date, int Montant, String Motif,int MontantTotal){
    try {
        ouverture();
    this.st=(Statement)this.con.createStatement();
this.requetteInserer="insert into dollar value('"+Nom+"','"+Postnom+"','"+Prenom+"','"+Date+"','"+Montant+"','"+Motif+"','"+MontantTotal+"')";
    this.st.executeUpdate(requetteInserer);
        JOptionPane.showMessageDialog(null," Enregistrer");
        fermeture();
    } catch (Exception e) {JOptionPane.showMessageDialog(null,"erreur \n "+e.getMessage());
    }
}

public void EntrerFranc(String Nom,String Postnom,String Prenom, String Date, int Montant, String Motif,int MontantTotal){
    try {
        ouverture();
    this.st=(Statement)this.con.createStatement();
this.requetteInserer="insert into franc value('"+Nom+"','"+Postnom+"','"+Prenom+"','"+Date+"','"+Montant+"','"+Motif+"','"+MontantTotal+"')";
    this.st.executeUpdate(requetteInserer);
        JOptionPane.showMessageDialog(null," Enregistrer");
        fermeture();
    } catch (Exception e) {JOptionPane.showMessageDialog(null,"erreur \n "+e.getMessage());
    }
}

}
