package ma_caisseremix;
import javax.swing.JOptionPane;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import javax.swing.Timer;


/**
 * Ma Caisse
 * @author G5 PROGS 
 * Kapend  Moise
 * Ntumba  Sephora
 * Nyota Falonne
 * Kamuanya Tabitha
 */
public class Authentification extends javax.swing.JFrame {
     private boolean fenetre=false;
         
private String url="jdbc:mysql://127.0.0.1:3306/finalcaisse",user="root",pass="";
   private Statement st;
   private Connection con;
   void ouverture(){
       try {
           Class.forName("com.mysql.jdbc.Driver");
           this.con=(Connection)DriverManager.getConnection(url, user,pass);
           System.out.println("bonne connexion");
       } catch (Exception e) {JOptionPane.showMessageDialog(null, e.getMessage());
       }
   }
   void fermeture(){
       try {
           this.st.close();
           this.con.close();
       } catch (Exception e) {
       }
   }

    /**
     * Creates new form Authentification
     */
    public Authentification() {
        initComponents();
         Timer updateTimer;
        int play=100;
        updateTimer=new Timer(play,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date cur= new Date();   
                String FormatTimer="hh:mm:ss";
                String FormatTimer2="dd/MM/yyyy";
                DateFormat as=new SimpleDateFormat(FormatTimer);
                DateFormat ase=new SimpleDateFormat(FormatTimer2);
                String a=as.format(cur);
                String b=ase.format(cur);
                heure.setText(a);
                date.setText(b);
                
            }
        });
        updateTimer.start();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BoutonFermer = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        BoutonParametre = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        heure = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BoutonOK = new javax.swing.JButton();
        motdepasse = new javax.swing.JPasswordField();
        date = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        BoutonFermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ma_caisseremix/Images/exit.png"))); // NOI18N
        BoutonFermer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BoutonFermer.setFocusCycleRoot(true);
        BoutonFermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoutonFermerMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nouveau compte");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ma_caisseremix/Images/g22252.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Fermer");

        BoutonParametre.setBackground(new java.awt.Color(255, 255, 255));
        BoutonParametre.setForeground(new java.awt.Color(255, 255, 255));
        BoutonParametre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ma_caisseremix/Images/icons8_settings_50px.png"))); // NOI18N
        BoutonParametre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BoutonParametre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoutonParametreMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BoutonParametre)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(BoutonParametre)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(BoutonFermer)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BoutonFermer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ma Caisse");

        heure.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        heure.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(heure, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(heure, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 340, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Identifiez-vous");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 164, -1, -1));

        nom.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nom.setToolTipText("");
        nom.setActionCommand("<Not Set>");
        nom.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        nom.setName(""); // NOI18N
        jPanel1.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 237, 142, 32));
        nom.getAccessibleContext().setAccessibleName("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ma_caisseremix/Images/icons8_user_32px.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 237, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ma_caisseremix/Images/icons8_password_32px.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 315, -1, -1));

        BoutonOK.setBackground(new java.awt.Color(0, 0, 153));
        BoutonOK.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BoutonOK.setForeground(new java.awt.Color(255, 255, 255));
        BoutonOK.setText("Ok");
        BoutonOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BoutonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonOKActionPerformed(evt);
            }
        });
        jPanel1.add(BoutonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 403, 73, 36));

        motdepasse.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        motdepasse.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(motdepasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 315, 148, 32));

        date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 468, 122, 24));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 275, 184, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 353, 184, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*methode du bouton fermer*/
    private void BoutonFermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoutonFermerMouseClicked
        // Fermer:
        int option=JOptionPane.showConfirmDialog(null, "Voulez-vous fermer le programme?","Quitter",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(option == JOptionPane.OK_OPTION){
           
            JOptionPane.showMessageDialog(null,"Gestion de Ma Caisse","Ma caisse",JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            new Authentification().setVisible(true);
        }
      
        this.dispose();
    }//GEN-LAST:event_BoutonFermerMouseClicked
/*methode du bouton parametre*/
    private void BoutonParametreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoutonParametreMouseClicked
        // Configuration de l'utilisateur du PC:
        if (evt.getClickCount()==5){
            if(fenetre == false){
                fenetre=true;
                int mdp;
                mdp=Integer.parseInt(JOptionPane.showInputDialog("Mot de passe Administrateur!"));
                if(mdp == 129012345){
                    this.dispose();
                    new Configuration_Utilisateur().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null,"Mot de passe invalide\nContactez les Administrateurs!!");  
                }
            }
        }
        
    }//GEN-LAST:event_BoutonParametreMouseClicked
/*methode du bouton ok*/
    private void BoutonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonOKActionPerformed
        // La verification:
        authentif();
    }//GEN-LAST:event_BoutonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BoutonFermer;
    private javax.swing.JButton BoutonOK;
    private javax.swing.JLabel BoutonParametre;
    private javax.swing.JLabel date;
    private javax.swing.JLabel heure;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField motdepasse;
    private javax.swing.JTextField nom;
    // End of variables declaration//GEN-END:variables

    /*     creation de la     Methode de verification de l'utilisateur*/
    
    public void authentif(){//methode d'authentification
     try{
            ouverture();//methode pour ouvrire la base de donnees 
            String utilisateur = nom.getText();//variable de type chaine des characteres 
            String MOTDEPASSE = motdepasse.getText();//variable de type chaine des characteres 
            //ces deux variables sont utiles pour verifier ce que l'utilisateur saisie au niveau de jtextfield
            Statement stm =(Statement) con.createStatement();//une de methode pour  fouiller dans la BD
            //le ligne qui suit permet juste de verifier deux informations inserer dans la BD
            //ici on prend tout simplement le nom et le mot de passe:
            String sql ="select * from proprio where NOM ='"+utilisateur+"' and "
                    + "code = '"+MOTDEPASSE+"' ";
            /*cette methode je ne la connais pas vraiment , mais je pense que ca permet 
                    d'effectuer une recherche ligne apres ligne dans la base de donnees*/
            ResultSet rs = stm.executeQuery(sql);
            //la condition pour voir..si les deux informations saisies dans le jtxetfield sont correct.
            if(rs.next()){
               this.dispose();
               new Choix().setVisible(true);
            }else{//sinon , on lui envoie une notification d'erreure et on renitialise les deux zones de saisies
                JOptionPane.showMessageDialog(this,"Oups!! \nNom ou Mot de passe incorrect");//message d'erreure
                nom.setText("");
                motdepasse.setText(null);
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        } 
}
    
}
