package ma_caisseremix;
/*Les imports */
 
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
/**
 * Ma Caisse
 * @author G5 PROGS 
 * Kapend  Moise
 * Ntumba  Sephora
 * Nyota Falonne
 * Kamuanya Tabitha
 */
public class Bilan extends javax.swing.JFrame {
    private String url="jdbc:mysql://127.0.0.1:3306/finalcaisse",user="root",pass="";
  private Statement st;
  private String requetteVerifier;
  private String requetteAide;
  private String requetteEnregisBilan;
  private String requetteInserer;
  private Connection con; 
  private String devise;
  private String rec;
  private String rech;
  void ouverture(){
      try {
          Class.forName("com.mysql.jdbc.Driver");
          this.con=(Connection)DriverManager.getConnection(url,user,pass);
          System.out.println("c'est bon");
      } catch (Exception e) {JOptionPane.showMessageDialog(null,""+e.getMessage());
      }
  }
  void fermeture(){
      try {
          this.con.close();
          this.st.close();
          System.out.println("ferme");
      } catch (Exception e) {JOptionPane.showMessageDialog(null,""+e.getMessage());
      }
}

    /**
     * Creates new form Bilan
     */
    public Bilan() {
        initComponents();
        
         Timer updateTimer;
        int play=100;
        updateTimer=new Timer(play,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date cur= new Date();   
                String FormatTimer="hh:mm:ss";
                String FormatTimer2="dd/MM/yyyy";
                DateFormat as=new SimpleDateFormat(FormatTimer);
                DateFormat ase=new SimpleDateFormat(FormatTimer2);
                String a=as.format(cur);
                String b=ase.format(cur);
                heure.setText(a);
                date.setText(b);
                
            }
        });
        updateTimer.start();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BoutonFermer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        opp = new javax.swing.JComboBox<>();
        BoutonAccueil = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        pre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BoutonVerifier = new javax.swing.JButton();
        post = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BoutonPrintù = new javax.swing.JButton();
        heure = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        montantdollar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        montantfranc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        fraisf = new javax.swing.JTextField();
        fraisd = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fraisdollar = new javax.swing.JLabel();
        fraisfranc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("BILAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 0, -1, -1));

        BoutonFermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ma_caisseremix/Images/exit.png"))); // NOI18N
        BoutonFermer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BoutonFermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoutonFermerMouseClicked(evt);
            }
        });
        jPanel1.add(BoutonFermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(894, 10, -1, -1));

        tab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOM", "POSTNOM", "PRENOM", "MOTIF", "MONTANT", "M-TOTAL", "DATE"
            }
        ));
        jScrollPane1.setViewportView(tab);
        if (tab.getColumnModel().getColumnCount() > 0) {
            tab.getColumnModel().getColumn(6).setResizable(false);
            tab.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 116, 598, 242));

        opp.setBackground(new java.awt.Color(204, 255, 255));
        opp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FRANC", "DOLLAR" }));
        jPanel1.add(opp, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 368, 91, 33));

        BoutonAccueil.setBackground(new java.awt.Color(102, 0, 51));
        BoutonAccueil.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BoutonAccueil.setText("ACCUEIL");
        BoutonAccueil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BoutonAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAccueilActionPerformed(evt);
            }
        });
        jPanel1.add(BoutonAccueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 512, -1, 36));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations sur le client"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("POSTNOM:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 70, -1, -1));

        nom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        jPanel3.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 25, 109, -1));

        pre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preActionPerformed(evt);
            }
        });
        jPanel3.add(pre, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 117, 109, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("NOM:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, -1, -1));

        BoutonVerifier.setBackground(new java.awt.Color(0, 0, 153));
        BoutonVerifier.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BoutonVerifier.setText("VERIFIER");
        BoutonVerifier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BoutonVerifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonVerifierActionPerformed(evt);
            }
        });
        jPanel3.add(BoutonVerifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 191, -1, 35));

        post.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 68, 109, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("PRENOM:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 119, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, 270, 240));

        BoutonPrintù.setBackground(new java.awt.Color(51, 0, 153));
        BoutonPrintù.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BoutonPrintù.setText("PRINT");
        BoutonPrintù.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BoutonPrintù.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonPrintùActionPerformed(evt);
            }
        });
        jPanel1.add(BoutonPrintù, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 370, 87, 38));

        heure.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        heure.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(heure, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 25, 203, 30));

        date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 516, 165, 32));

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Disponible", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        montantdollar.setEditable(false);
        montantdollar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel4.add(montantdollar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 29, 70, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("$");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 33, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("FC");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 77, -1, -1));

        montantfranc.setEditable(false);
        montantfranc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel4.add(montantfranc, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 73, 70, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 387, -1, 110));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DEVISE:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 372, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FRAIS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fraisf.setEditable(false);
        fraisf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel5.add(fraisf, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 76, 93, -1));

        fraisd.setEditable(false);
        fraisd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel5.add(fraisd, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 29, 93, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setText("$");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 33, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setText("Fc");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 73, 35, 29));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 387, -1, 110));
        jPanel1.add(fraisdollar, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 0, 52, 36));
        jPanel1.add(fraisfranc, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 42, 52, 36));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*pas util*/
    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
    }//GEN-LAST:event_nomActionPerformed
    private void preActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preActionPerformed
    }//GEN-LAST:event_preActionPerformed
/*methode du bouton fermer*/
    private void BoutonFermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoutonFermerMouseClicked
        // TODO add your handling code here:
        int option=JOptionPane.showConfirmDialog(null, "Voulez-vous fermer le programme?","Quitter",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(option == JOptionPane.OK_OPTION){
           
            JOptionPane.showMessageDialog(null,"Gestion de Ma Caisse","Ma caisse",JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            new Bilan().setVisible(true);
        }
        this.dispose();
        
    }//GEN-LAST:event_BoutonFermerMouseClicked
/*methode du bouton accueil*/
    private void BoutonAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAccueilActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Choix().setVisible(true);
    }//GEN-LAST:event_BoutonAccueilActionPerformed
/* methode du bouton verifier*/
    private void BoutonVerifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonVerifierActionPerformed
        // Verifier:
String choix=(String)opp.getSelectedItem();
if(choix.equals("FRANC")){selectFranc(nom.getText(),post.getText(),pre.getText());}
if(choix.equals("DOLLAR")){selectDollar(nom.getText(),post.getText(),pre.getText());}

    }//GEN-LAST:event_BoutonVerifierActionPerformed
/*methode print*/
    private void BoutonPrintùActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonPrintùActionPerformed
        // Pour imprimer:
        MessageFormat header=new MessageFormat("Bilan");
        MessageFormat footer=new MessageFormat("Merci d'avoir utiisé notre service");
        try {
            tab.print(JTable.PrintMode.NORMAL,header,footer);
        } catch (java.awt.print.PrinterException e) {System.err.format(" erreur d'impression",e.getMessage());
        }
    }//GEN-LAST:event_BoutonPrintùActionPerformed
  
    /* methode une fois que l'interface s'ouvre*/
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        prendreFraisDollar();
        prendreFraisFranc();
        RechercheDollar();
        RechercheFranc();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonAccueil;
    private javax.swing.JLabel BoutonFermer;
    private javax.swing.JButton BoutonPrintù;
    private javax.swing.JButton BoutonVerifier;
    private javax.swing.JLabel date;
    private javax.swing.JTextField fraisd;
    private javax.swing.JLabel fraisdollar;
    private javax.swing.JTextField fraisf;
    private javax.swing.JLabel fraisfranc;
    private javax.swing.JLabel heure;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField montantdollar;
    private javax.swing.JTextField montantfranc;
    private javax.swing.JTextField nom;
    private javax.swing.JComboBox<String> opp;
    private javax.swing.JTextField post;
    private javax.swing.JTextField pre;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables

    /*   Recherche et  Verification du client dans la base de donnee*/
    
public void selectFranc(String nom,String post,String pre){
    try {
        ouverture();
        this.st=(Statement)this.con.createStatement();
        this.rec="Select * from ajoutclient where Nom='"+nom+"' and Postnom='"+post+"' and Prenom='"+pre+"'";
        
        ResultSet rs=st.executeQuery(rec);
        if(rs.next()){
            selectFra(nom, post, pre);
           }
        else{
            JOptionPane.showMessageDialog(null,"Oups \nClient introuvable!!");
            
        }
        
        fermeture();
    } catch (SQLException e) {JOptionPane.showMessageDialog(null,"erreur "+e.getMessage());
    }
}
      
      
      /*  Recherche et  Verification du compte dollar du client*/
      
public void selectDollar(String nom,String post,String pre){
    try {
        ouverture();
        this.st=(Statement)this.con.createStatement();
        //String recher="select * from client where 1";
        this.rec="Select * from ajoutclient where Nom='"+nom+"' and Postnom='"+post+"' and Prenom='"+pre+"'";
        
        ResultSet rs=st.executeQuery(rec);
        if(rs.next()){
            selectDol(nom, post, pre);
           }
         else{
            JOptionPane.showMessageDialog(null,"Oups \nClient introuvable!!");
        }
        fermeture();
    } catch (SQLException e) {JOptionPane.showMessageDialog(null,"erreur "+e.getMessage());
    }
}
        
       /*      Selection et affichage du compte dollar du client*/
        
public void selectFra(String nom,String post,String pre){
    try {
        ouverture();
        this.st=(Statement)this.con.createStatement();
            this.rech="select *  from franc where Nom='"+nom+"' and Postnom='"+post+"' and Prenom='"+pre+"'";
            ResultSet r=st.executeQuery(rech);
        while(r.next())   
        {
             String NOm=r.getString("Nom");
             String POstnom=r.getString("Postnom");
             String PRenom=r.getString("Prenom");
             String MOntant=r.getString("Montant");
             String MOtif=r.getString("Motif");
             String MOntantTotal=r.getString("MontantTotal");
             MOntantTotal=MOntantTotal+" fc";
             MOntant=MOntant+" fc";
             String DAte=r.getString("Date");
             String montant[]={NOm,POstnom,PRenom,MOtif,MOntant,MOntantTotal,DAte};
             DefaultTableModel tqbi=(DefaultTableModel)tab.getModel();
                     tqbi.addRow(montant);
        }
        
        fermeture();
    } catch (SQLException e) {JOptionPane.showMessageDialog(null,"erreur "+e.getMessage());
    }
}
        
        /*      Selection et affichage du compte dollar du client*/
        
public void selectDol(String nom,String post,String pre){
    try {
        ouverture();
        this.st=(Statement)this.con.createStatement();
            this.rech="select *  from dollar where Nom='"+nom+"' and Postnom='"+post+"' and Prenom='"+pre+"'";
            ResultSet r=st.executeQuery(rech);
        while(r.next())   
        {
             String NOm=r.getString("Nom");
             String POstnom=r.getString("Postnom");
             String PRenom=r.getString("Prenom");
             String MOntant=r.getString("Montant");
             MOntant=MOntant+" $";
             String DAte=r.getString("Date");
             String MOtif=r.getString("Motif");
            String MOntantTotal=r.getString("MontantTotal");
            MOntantTotal=MOntantTotal+" $";
             String montant[]={NOm,POstnom,PRenom,MOtif,MOntant,MOntantTotal,DAte};
             DefaultTableModel tqbi=(DefaultTableModel)tab.getModel();
                     tqbi.addRow(montant);
        }
        
        fermeture();
    } catch (SQLException e) {JOptionPane.showMessageDialog(null,"erreur "+e.getMessage());
    }
}
       
           /*      affichage du bilan Dollar que le proprietaire garde*/
           
           
 public void RechercheFranc(){
    try {
        ouverture();
        this.st=(Statement)this.con.createStatement();
        this.rech="select Montant2 from bilan2 where1 ";
        ResultSet rs=st.executeQuery(rech);
        while(rs.next())   
        {
            int monnn=rs.getInt("Montant2");
            montantfranc.setText(""+monnn);
        }
        fermeture();
    } catch (SQLException e) {JOptionPane.showMessageDialog(null,"erreur "+e.getMessage());
    }
}
            
 /*      affichage du bilan Dollar que le proprietaire garde*/
            
 public void RechercheDollar(){
    try {
        ouverture();
        this.st=(Statement)this.con.createStatement();
        this.rech="select Montant from bilan where 1 ";
        ResultSet rs=st.executeQuery(rech);
        while(rs.next())   
        {
            int monn=rs.getInt("Montant"); 
            montantdollar.setText(""+monn);
        }
        fermeture();
    } catch (SQLException e) {JOptionPane.showMessageDialog(null,"erreur "+e.getMessage());
    }
}
 
  /*         Methode de selection du frais dollar*/
 
 public void prendreFraisDollar(){
     try{
         ouverture();
         this.st=(Statement)this.con.createStatement();
        this.requetteVerifier="Select Montant1 From frais1 where 1";
        ResultSet rs = this.st.executeQuery(requetteVerifier);
        while(rs.next())
        {
            int ga =rs.getInt("montant1");
            fraisd.setText(""+ga);
        }
         fermeture();
     }catch(Exception e){
         
     }
 }
 
 /*         Methode de selection du frais franc*/
 
 public void prendreFraisFranc(){
     try{
         ouverture();
          this.st=(Statement)this.con.createStatement();
        this.requetteVerifier="Select Montant From frais where 1";
        ResultSet rs = this.st.executeQuery(requetteVerifier);
        while(rs.next())
        {
            int ag =rs.getInt("montant");
            fraisf.setText(""+ag);
        }
         fermeture();
     }catch(Exception e){
         
     }
 }
           
}
