package boxchat;

import java.sql.DriverManager;
import com.mysql.jdbc.Statement;
import com.mysql.jdbc.Connection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Timer;
import java.util.TimerTask;
/**
 * @author Moses
 */
public class msg extends javax.swing.JFrame {
    private final String url ="jdbc:mysql://127.0.0.1:3306/box";
    private final String user ="root";
    private final String pass ="";
    private Statement st;
    private Connection con;

void ouverture(){
    try {
        Class.forName("com.mysql.jdbc.Driver");
        this.con =(Connection)DriverManager.getConnection(url,user,pass);
        System.out.println("ok");
    } catch (Exception e) {
        System.out.println("pas ok con");
    }
}
void fermeture(){
    try {
        this.con.close();
        this.st.close();
        System.out.println("ok close");
    } catch (Exception e) {
        System.out.println("pas ok close");
    }
    
}
    
    

    /**
     * Creates new form msg
     */
    public msg() {
        initComponents();
        prendre();
        prendre1();
        try {
            charge();
        } catch (Exception ex) {
            Logger.getLogger(msg.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        int delay = 1000; //milliseconds
        ActionListener taskPerformer;
        taskPerformer = (ActionEvent evt) -> {
            System.out.println("1");
        };
        Timer t = new Timer(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telt = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        recois2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        envoie2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        telm = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        envoie1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        recois1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        telt.setBackground(new java.awt.Color(102, 102, 102));

        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        recois2.setEditable(false);
        recois2.setColumns(20);
        recois2.setRows(5);
        jScrollPane3.setViewportView(recois2);

        envoie2.setColumns(20);
        envoie2.setRows(5);
        jScrollPane4.setViewportView(envoie2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("TOI");

        javax.swing.GroupLayout teltLayout = new javax.swing.GroupLayout(telt);
        telt.setLayout(teltLayout);
        teltLayout.setHorizontalGroup(
            teltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teltLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(34, 34, 34))
            .addGroup(teltLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel2)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(teltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(teltLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(teltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(teltLayout.createSequentialGroup()
                            .addGap(0, 65, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(teltLayout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65)))
                    .addContainerGap()))
        );
        teltLayout.setVerticalGroup(
            teltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teltLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(313, 313, 313)
                .addComponent(jButton2)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(teltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(teltLayout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(117, Short.MAX_VALUE)))
        );

        telm.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        envoie1.setColumns(20);
        envoie1.setRows(5);
        jScrollPane1.setViewportView(envoie1);

        recois1.setEditable(false);
        recois1.setColumns(20);
        recois1.setRows(5);
        jScrollPane2.setViewportView(recois1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MOI");

        javax.swing.GroupLayout telmLayout = new javax.swing.GroupLayout(telm);
        telm.setLayout(telmLayout);
        telmLayout.setHorizontalGroup(
            telmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telmLayout.createSequentialGroup()
                        .addGap(0, 65, Short.MAX_VALUE)
                        .addGroup(telmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telmLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telmLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(telmLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(telmLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        telmLayout.setVerticalGroup(
            telmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telmLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(telm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(telt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        send(envoie1.getText());
        rr();
        
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        send1(envoie2.getText());
        rr();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        //methode ici:
        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(msg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(msg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(msg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(msg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new msg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea envoie1;
    private javax.swing.JTextArea envoie2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea recois1;
    private javax.swing.JTextArea recois2;
    private javax.swing.JPanel telm;
    private javax.swing.JPanel telt;
    // End of variables declaration//GEN-END:variables

    public void send(String E){
        try {
            ouverture();
            this.st=(Statement)this.con.createStatement();
            String rq="insert into toi value('"+E+"')";
            this.st.executeUpdate(rq);
            fermeture();
            
        } catch (Exception e) {
        }
        
    }
    
    public void send1(String E){
        try {
            ouverture();
            this.st=(Statement)this.con.createStatement();
            String rq="insert into moi value('"+E+"')";
            this.st.executeUpdate(rq);
            fermeture();
        } catch (Exception e) {
        }
        
    }
    public void prendre(){
        try {
            ouverture();
            Statement st = (Statement) con.createStatement();
            String sql = "select message from toi";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String NOM = rs.getString("message");
                recois1.setText(NOM);
            }
        } catch (Exception e) {
        }
    }
    public void prendre1(){
        try {
            ouverture();
            Statement st = (Statement) con.createStatement();
            String sql = "select message from moi";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String NOM = rs.getString("message");
                recois2.setText(NOM);
            }
        } catch (Exception e) {
        }
    }
    public void charge()throws Exception{
        for (int i = 0; i < 100; i++) {
             java.util.Timer tm = new java.util.Timer();
             
             telt.updateUI();
        }
       
    }
    public void rr(){
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                telt.getComponents();
                telm.getComponents();
            }
        };
        Timer timer = new Timer(true);
        timer.schedule(task,0,1000);
        for (int i = 0; i < 4; i++) {
            System.out.println(i);
            try{
            Thread.sleep(1000);
            }catch(Exception e){}
        }
    }
}
