/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ma_caisse_Remix_20;

import java.awt.Toolkit;

/**
 *
 * @author Moses
 */
public class charge extends javax.swing.JFrame {

    /**
     * Creates new form charge
     */
    public charge() {

        initComponents();
        setIcone();
       /* h.setVisible(false);
        o.setVisible(false);
        s.setVisible(false);
        t.setVisible(false);
        o1.setVisible(false);
        dp.setVisible(false);
        s1.setVisible(false);
        y.setVisible(false);
        n.setVisible(false);
        a.setVisible(false);
        log.setVisible(false);*/
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bar = new javax.swing.JProgressBar();
        co1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 483, 620, 20));

        co1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        co1.setText("0");
        jPanel1.add(co1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        charge ch = new charge();
        ch.setVisible(true);
        for (int i = 0; i <= 101; i++) {
            Thread.sleep(30);
            ch.bar.setValue(i);
            ch.co1.setText(i + "%");
            /*switch (i) {
                case 2:
                    ch.h.setVisible(true);
                    break;
                    
                case 10:
                    ch.o.setVisible(true);
                    break;
                case 20:
                    ch.s.setVisible(true);
                    break;
                case 30:
                    ch.t.setVisible(true);
                    ch.log.setVisible(true);
                    break;
                case 40:
                    ch.o1.setVisible(true);
                    break;
                case 50:
                    ch.dp.setVisible(true);
                    break;
                case 60:
                    ch.s1.setVisible(true);
                    break;
                case 70:
                    ch.y.setVisible(true);
                    break;
                case 80:
                    ch.n.setVisible(true);
                    break;
                case 90:
                    ch.a.setVisible(true);
                    break;
                case 100:
                    break;

            }*/

        }
        ch.setVisible(false);
        new MENU_EXCEL().setVisible(true);
        // new authentification().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JLabel co1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void setIcone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("img0.jpg")));
    }
}
