/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package introduction;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Diagnostique extends javax.swing.JFrame {
    ArrayList<String> arl=new ArrayList<>();
    /**
     * Creates new form Diagnostique
     */
    static String prenom;
    public Diagnostique(String prenom) {
        initComponents();
        setResizable(false);
        this.prenom = prenom;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mdg = new javax.swing.JCheckBox();
        mdv = new javax.swing.JCheckBox();
        mdt = new javax.swing.JCheckBox();
        vom = new javax.swing.JCheckBox();
        yj = new javax.swing.JCheckBox();
        vertige = new javax.swing.JCheckBox();
        nqc = new javax.swing.JCheckBox();
        toux = new javax.swing.JCheckBox();
        dia = new javax.swing.JCheckBox();
        fiev = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mdg.setFont(new java.awt.Font("Bell MT", 1, 11)); // NOI18N
        mdg.setText("MAUX DE GORGE");

        mdv.setFont(new java.awt.Font("Bell MT", 1, 11)); // NOI18N
        mdv.setText("MAUX DE VENTRE");

        mdt.setFont(new java.awt.Font("Bell MT", 1, 11)); // NOI18N
        mdt.setText("MAUX DE TETE");

        vom.setFont(new java.awt.Font("Bell MT", 1, 11)); // NOI18N
        vom.setText("VOMISSEMENT");

        yj.setFont(new java.awt.Font("Bell MT", 1, 11)); // NOI18N
        yj.setText("YEUX JAUNE");
        yj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yjActionPerformed(evt);
            }
        });

        vertige.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        vertige.setText("VERTIGE");

        nqc.setFont(new java.awt.Font("Bell MT", 1, 11)); // NOI18N
        nqc.setText("NEZ QUI COULE");
        nqc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nqcActionPerformed(evt);
            }
        });

        toux.setFont(new java.awt.Font("Bell MT", 1, 11)); // NOI18N
        toux.setText("TOUX");
        toux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                touxActionPerformed(evt);
            }
        });

        dia.setFont(new java.awt.Font("Bell MT", 1, 11)); // NOI18N
        dia.setText("DIARHEE");

        fiev.setFont(new java.awt.Font("Bell MT", 1, 11)); // NOI18N
        fiev.setText("FIEVRE");
        fiev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fievActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/OK.jpeg"))); // NOI18N
        jButton2.setText("VALIDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/accueilIcon.jpeg"))); // NOI18N
        jButton1.setText("ACCUEIL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mdg, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(fiev, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mdv, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mdt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(toux, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vom, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(nqc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yj, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(vertige, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mdg)
                    .addComponent(fiev))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mdv)
                    .addComponent(dia))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mdt)
                    .addComponent(toux))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vom)
                    .addComponent(nqc))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yj)
                    .addComponent(vertige))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(471, 397));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        acceuil ac = new acceuil(prenom);
        ac.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(mdg.isSelected()){
            arl.add(mdg.getText());
        }
        if(mdv.isSelected()){
            arl.add(mdv.getText());
        }
        if (mdt.isSelected()){
            arl.add(mdt.getText());
        }
        if (vom.isSelected()){
            arl.add(vom.getText());
        }
        if (yj.isSelected()){
            arl.add(yj.getText());
        }
        if (fiev.isSelected()){
            arl.add(fiev.getText());
        }
        if (dia.isSelected()){
            arl.add(dia.getText());
        }
        if (toux.isSelected()){
            arl.add(toux.getText());
        }
        if (nqc.isSelected()){
            arl.add(nqc.getText());
        }
        if (vertige.isSelected()){
            arl.add(vertige.getText());
        }
        if(arl.isEmpty()){
            JOptionPane.showMessageDialog(null, "Afin d'obtenir un resultat veuillez en choisir au moins un");
        }else{
            this.hide();
            resultat rseult=new resultat(arl);
            rseult.setVisible(true);
            arl.clear();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void nqcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nqcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nqcActionPerformed

    private void touxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_touxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_touxActionPerformed

    private void yjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yjActionPerformed

    private void fievActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fievActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fievActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnostique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnostique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnostique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnostique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnostique(prenom).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox dia;
    private javax.swing.JCheckBox fiev;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox mdg;
    private javax.swing.JCheckBox mdt;
    private javax.swing.JCheckBox mdv;
    private javax.swing.JCheckBox nqc;
    private javax.swing.JCheckBox toux;
    private javax.swing.JCheckBox vertige;
    private javax.swing.JCheckBox vom;
    private javax.swing.JCheckBox yj;
    // End of variables declaration//GEN-END:variables
}
