/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package introduction;

import javax.swing.JOptionPane;



/**
 *
 * @author Devernay Mbala
 */
public class new_compte extends javax.swing.JFrame {

    /**
     * Creates new form new_compte
     */
    public new_compte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("C'est notre priorité.\"");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 200, 190, 30);

        jLabel4.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("CONSEILS SANTE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 20, 330, 80);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 24)); // NOI18N
        jLabel3.setText("\"Votre santé passe avant tout.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 150, 310, 40);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inscrivez-vous");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(23, 11, 340, 33);

        jLabel10.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/apro.png"))); // NOI18N
        jLabel10.setText("Prénom :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 42, 120, 40);

        jLabel11.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/taille.png"))); // NOI18N
        jLabel11.setText("Taille(en cm) : ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(23, 89, 161, 22);

        jTextField4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jTextField4.setToolTipText("Prénom");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(163, 50, 260, 30);

        jTextField5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jTextField5.setToolTipText("Entrer votre taille");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(186, 87, 68, 30);

        jLabel12.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/poids.png"))); // NOI18N
        jLabel12.setText("Poids(en kg) : ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(23, 126, 159, 22);

        jTextField6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jTextField6.setToolTipText("Entrer votre poids ");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(190, 124, 67, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        jRadioButton1.setText("Homme");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(310, 120, 91, 33);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        jRadioButton2.setText("Femme");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(310, 162, 100, 33);

        jLabel13.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/age.png"))); // NOI18N
        jLabel13.setText("Age :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 170, 79, 22);

        jTextField8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jTextField8.setToolTipText("Entrer votre age");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(190, 170, 68, 30);

        jLabel15.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/àpropos.png"))); // NOI18N
        jLabel15.setText("Nom d'utilisateur :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(0, 250, 191, 30);

        jTextField9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jTextField9.setToolTipText("Entrer votre nom d'utilisateur");
        jPanel1.add(jTextField9);
        jTextField9.setBounds(190, 250, 151, 30);

        jLabel16.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/clé1.png"))); // NOI18N
        jLabel16.setText("Mot de passe :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 290, 150, 22);

        jTextField10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jTextField10.setToolTipText("Entrer votre mot de passe");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10);
        jTextField10.setBounds(190, 290, 151, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/OK.jpeg"))); // NOI18N
        jButton1.setText("OK");
        jButton1.setToolTipText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 370, 180, 43);

        jLabel17.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/clé1.png"))); // NOI18N
        jLabel17.setText("Confirmer Mdp :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(9, 330, 170, 22);

        jTextField11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jTextField11.setToolTipText("Confirmer le mot de passe");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField11);
        jTextField11.setBounds(190, 330, 151, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/retour.png"))); // NOI18N
        jButton2.setText("RETOUR");
        jButton2.setToolTipText("Retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(216, 370, 230, 43);

        jLabel18.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/commune.png"))); // NOI18N
        jLabel18.setText("Commune habitée :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(20, 202, 180, 35);

        jComboBox1.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ndjili", "Kasa-Vubu", "Lingwala", "Maluku", "Kinkole", "Gombe", "Ngaba", "Ngiri-Ngiri", "Limete", "Masina", "Kimbanseke", "Nsele", "Matete", "Lemba", "Kinshasa", "Barumbu", "Kintambo", "Bandal", "Bumbu", "Selembao", "Makala", "Mont Ngafula", "Ngaliema", "Kalamu" }));
        jComboBox1.setToolTipText("Sélectionner votre commune habitée ");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(210, 210, 240, 28);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 320, 270, 10);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(410, 10, 460, 440);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/connexion_img.jpg"))); // NOI18N
        jLabel9.setText("jLabel1");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 910, 460);

        setSize(new java.awt.Dimension(919, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String prenom = jTextField4.getText();
       double Taille = Double.parseDouble(jTextField5.getText());
                
        double Poids = Double.parseDouble(jTextField6.getText());
        int Age = Integer.parseInt(jTextField8.getText());
        String Sexe = "";
        if(jRadioButton1.isSelected()){
            Sexe = jRadioButton1.getText();
        }
        else if(jRadioButton2.isSelected()){
            Sexe = jRadioButton2.getText();
        }
        else if(!jRadioButton1.isSelected() || !jRadioButton2.isSelected()){
            JOptionPane.showMessageDialog(null, "Choisissez le sexe");
        }
        
        
         String Commune_habite = jComboBox1.getSelectedItem().toString(); 
         System.err.println(Sexe);
        String Nom_utilisateur = jTextField9.getText();
        String mot_passe = jTextField10.getText();
        
        String confirm = jTextField11.getText();
        
        System.out.println(Sexe);
        
       System.out.println("mot_passe est  " + mot_passe);
       System.out.println("confirme est  " + confirm);
        
      /* if(Prenom.isEmpty() || Taille.isEmpty() || Poids.isEmpty() || Age.isEmpty() || Nom_utilisateur.isEmpty() || mot_passe.isEmpty() || confirm.isEmpty())
       {
           jLabel11.setText("Veuillez remplir tous les champs");
       }
       */
       
        if(!mot_passe.equals(confirm))
        {
            jLabel1.setText("Les mots de passe ne sont pas cohérents");
        }
        else
        {
            
            connect.enregistrement(prenom,Taille,Poids,Age,Sexe,Commune_habite,Nom_utilisateur, mot_passe);
            JOptionPane.showMessageDialog(null,"Votre compte a été créé avec succès");
            acceuil ac = new acceuil(prenom);
            ac.setVisible(true); 
            this.hide();
             
            
            
        }
        
       
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        connexion con = new connexion();
        con.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_compte().setVisible(true);
            }
        });
    }
    
    
    Connecter connect = new Connecter();
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    
}
