package testinterf;

import java.awt.Color;
import java.util.Random;

/**
 *
 * @author Moses
 */
public class un extends javax.swing.JFrame {

    /**
     * Creates new form un
     */
    public un() {
        initComponents();
        sh.setVisible(false);
        sc.setVisible(false);
        b.setVisible(false);
        bl.setVisible(false);
        g.setVisible(false);
        gr.setVisible(false);
        o.setVisible(false);
        r.setVisible(false);
        tr.setText(null);
        fl.setText(null);
        sh.setBackground(couleurAleatoire());
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        sh = new javax.swing.JPanel();
        bl = new javax.swing.JButton();
        r = new javax.swing.JButton();
        b = new javax.swing.JButton();
        g = new javax.swing.JButton();
        o = new javax.swing.JButton();
        gr = new javax.swing.JButton();
        sc = new javax.swing.JPanel();
        tr = new javax.swing.JLabel();
        fl = new javax.swing.JLabel();
        truec = new javax.swing.JLabel();
        falsec = new javax.swing.JLabel();
        txtsc = new javax.swing.JLabel();
        n = new javax.swing.JButton();
        txt = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        sh.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                shMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                shMouseMoved(evt);
            }
        });
        sh.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                shPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout shLayout = new javax.swing.GroupLayout(sh);
        sh.setLayout(shLayout);
        shLayout.setHorizontalGroup(
            shLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );
        shLayout.setVerticalGroup(
            shLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        bl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bl.setText("Black");
        bl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blActionPerformed(evt);
            }
        });

        r.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r.setText("Red");
        r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rActionPerformed(evt);
            }
        });

        b.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b.setText("Blue");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        g.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        g.setText("Green");
        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });

        o.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        o.setText("Orange");
        o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oActionPerformed(evt);
            }
        });

        gr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gr.setText("Gray");
        gr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grActionPerformed(evt);
            }
        });

        tr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tr.setForeground(new java.awt.Color(0, 255, 51));
        tr.setText("jLabel1");

        fl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fl.setForeground(new java.awt.Color(255, 0, 0));
        fl.setText("jLabel1");

        truec.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        truec.setForeground(new java.awt.Color(0, 255, 51));
        truec.setText("0");

        falsec.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        falsec.setForeground(new java.awt.Color(0, 255, 51));
        falsec.setText("0");

        javax.swing.GroupLayout scLayout = new javax.swing.GroupLayout(sc);
        sc.setLayout(scLayout);
        scLayout.setHorizontalGroup(
            scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scLayout.createSequentialGroup()
                        .addComponent(fl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(falsec, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(scLayout.createSequentialGroup()
                        .addComponent(tr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(truec, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        scLayout.setVerticalGroup(
            scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tr)
                    .addComponent(truec))
                .addGap(18, 18, 18)
                .addGroup(scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fl)
                    .addComponent(falsec))
                .addContainerGap())
        );

        txtsc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsc.setText("0");

        n.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n.setText("New Game");
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        txt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt.setText("Best Score");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txt))
                            .addComponent(sep, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtsc)
                        .addGap(117, 117, 117)))
                .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addComponent(sh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gr, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt)
                                .addGap(6, 6, 6)
                                .addComponent(sep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txtsc))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(bl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(o, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gr, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(sc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 535, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blActionPerformed
        // TODO add your handling code here:
        if (sh.getBackground() == Color.black) {
            tr.setText("True");
            int t;
            t = Integer.parseInt("" + truec.getText());
            t = t + 1;
            truec.setText(""+t);
            fl.setText(null);
            sh.setBackground(couleurAleatoire());
        }
        else if (sh.getBackground() != Color.black) {
            fl.setText("False");
            int f;
            f = Integer.parseInt("" + falsec.getText());
            f = f + 1;
            falsec.setText("" + f);
            tr.setText(null);

            sh.setBackground(couleurAleatoire());
        }
    }//GEN-LAST:event_blActionPerformed

    private void rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rActionPerformed
        // TODO add your handling code here:

        if (sh.getBackground() == Color.red) {
            tr.setText("True");
            int t;
            t = Integer.parseInt("" + truec.getText());
            t = t + 1;
            truec.setText(""+t);
            fl.setText(null);
            sh.setBackground(couleurAleatoire());
        } else if (sh.getBackground() != Color.red) {
            fl.setText("False");
            int f;
            f = Integer.parseInt("" + falsec.getText());
            f = f + 1;
            falsec.setText("" + f);
            tr.setText(null);

            sh.setBackground(couleurAleatoire());
        }
    }//GEN-LAST:event_rActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
        if (sh.getBackground() == Color.blue) {
            tr.setText("True");
            int t;
            t = Integer.parseInt("" + truec.getText());
            t = t + 1;
            truec.setText(""+t);
            fl.setText(null);
            sh.setBackground(couleurAleatoire());
        } else if (sh.getBackground() != Color.blue) {
            fl.setText("False");
            int f;
            f = Integer.parseInt("" + falsec.getText());
            f = f + 1;
            falsec.setText("" + f);
            tr.setText(null);

            sh.setBackground(couleurAleatoire());
        }
    }//GEN-LAST:event_bActionPerformed

    private void oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oActionPerformed
        // TODO add your handling code here:
        if (sh.getBackground() == Color.orange) {
            tr.setText("True");
            int t;
            t = Integer.parseInt("" + truec.getText());
            t = t + 1;
            truec.setText(""+t);
            fl.setText(null);
            sh.setBackground(couleurAleatoire());
        } else if (sh.getBackground() != Color.orange) {
            fl.setText("False");
            int f;
            f = Integer.parseInt("" + falsec.getText());
            f = f + 1;
            falsec.setText("" + f);
            tr.setText(null);

            sh.setBackground(couleurAleatoire());
        }
    }//GEN-LAST:event_oActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
        // TODO add your handling code here:
        if (sh.getBackground() == Color.GREEN) {
            tr.setText("True");
            int t;
            t = Integer.parseInt("" + truec.getText());
            t = t + 1;
            truec.setText(""+t);
            fl.setText(null);
            sh.setBackground(couleurAleatoire());
        } else if (sh.getBackground() != Color.green) {
            fl.setText("False");
            int f;
            f = Integer.parseInt("" + falsec.getText());
            f = f + 1;
            falsec.setText("" + f);
            tr.setText(null);

            sh.setBackground(couleurAleatoire());
        }
    }//GEN-LAST:event_gActionPerformed

    private void grActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grActionPerformed
        // TODO add your handling code here:
        if (sh.getBackground() == Color.GRAY) {
            tr.setText("True");
            int t;
            t = Integer.parseInt("" + truec.getText());
            t = t + 1;
            truec.setText(""+t);
            fl.setText(null);
            sh.setBackground(couleurAleatoire());
        } else if (sh.getBackground() != Color.gray) {
            fl.setText("False");
            int f;
            f = Integer.parseInt("" + falsec.getText());
            f = f + 1;
            falsec.setText("" + f);
            tr.setText(null);

            sh.setBackground(couleurAleatoire());
        }
    }//GEN-LAST:event_grActionPerformed

    private void shPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_shPropertyChange

        // cc.setBackground(Color.black);
    }//GEN-LAST:event_shPropertyChange

    private void shMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_shMouseMoved

    private void shMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_shMouseDragged

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
        n.setVisible(false);
        sep.setVisible(false);
        txt.setVisible(false);
        txtsc.setVisible(false);
        sh.setVisible(true);
        sc.setVisible(true);
        b.setVisible(true);
        bl.setVisible(true);
        g.setVisible(true);
        gr.setVisible(true);
        o.setVisible(true);
        r.setVisible(true);

    }//GEN-LAST:event_nActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        un jo = new un();
        jo.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b;
    private javax.swing.JButton bl;
    private javax.swing.JLabel falsec;
    private javax.swing.JLabel fl;
    private javax.swing.JButton g;
    private javax.swing.JButton gr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton n;
    private javax.swing.JButton o;
    private javax.swing.JButton r;
    private javax.swing.JPanel sc;
    private javax.swing.JSeparator sep;
    private javax.swing.JPanel sh;
    private javax.swing.JLabel tr;
    private javax.swing.JLabel truec;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel txtsc;
    // End of variables declaration//GEN-END:variables

    private Color couleurAleatoire() {
        Random rand = new Random();
        switch (rand.nextInt(6)) {
            case 0:
                return Color.RED;
            case 1:
                return Color.black;
            case 2:
                return Color.green;
            case 3:
                return Color.blue;
            case 4:
                return Color.orange;
            default:
                return Color.gray;

        }
    }

}
